module.exports = {
    PORT: process.env.PORT,
    MONGO_URI: process.env.MONGO_URI,
    FAST_API_URL: process.env.FAST_API_URL,
    FRONTEND_ENDPOINT:process.env.FRONTEND_ENDPOINT,
    GOOGLE_AUTH_CLIENT_ID:process.env.GOOGLE_AUTH_CLIENT_ID,
    GOOGLE_AUTH_CLIENT_SECRET: process.env.GOOGLE_AUTH_CLIENT_SECRET,
    GOOGLE_TOKEN_ENDPOINT:process.env.GOOGLE_TOKEN_ENDPOINT,
    GOOGLE_REDIRECT_URI:process.env.GOOGLE_REDIRECT_URI,
    JWT_SECRET: process.env.JWT_SECRET,
    INTERNAL_API_KEY: process.env.INTERNAL_API_KEY
};